MOVIES = [
    "The Matrix",
    "The Pianist",
    "The Empire Strikes Back",
    "The Twilight Saga: Breaking Dawn - Part 1",
    "Se7en",
    "Harry Potter and the Sorcerer's Stone",
    "The Exorcist",
    "The Hunger Games",
    "The Lion King",
    "Saving Private Ryan",
    "The Hunger Games: Catching Fire",
    "A Beautiful Mind",
    "The Twilight Saga: Twilight",
    "Harry Potter and the Half-Blood Prince",
    "The Twilight Saga: Breaking Dawn - Part 2",
    "The Lord of the Rings: The Return of the King",
    "Terminator 2: Judgment Day",
    "Apocalypse Now",
    "Gladiator",
    "The Hunger Games: Mockingjay - Part 1",
    "Goodfellas",
    "The Twilight Saga: New Moon",
    "The Grand Budapest Hotel",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Psycho",
    "Requiem for a Dream",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Battle of the Five Armies",
    "Harry Potter and the Prisoner of Azkaban",
    "The Divergent Series: Insurgent",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Hunger Games: Mockingjay - Part 2",
    "The Godfather: Part III",
    "The Sixth Sense",
    "The Great Gatsby",
    "Star Wars: Episode IV - A New Hope",
    "Casablanca",
    "The Divergent Series: Allegiant",
    "Interstellar",
    "The Shining",
    "American Beauty",
    "The Godfather",
    "Harry Potter and the Goblet of Fire",
    "The Matrix Reloaded",
    "Fight Club",
    "The Terminator",
    "The Social Network",
    "The Maze Runner",
    "Harry Potter and the Deathly Hallows: Part 2",
    "The Dark Knight Rises",
    "The Chronicles of Narnia: Prince Caspian",
    "The Silence of the Lambs",
    "The Revenant",
    "The Green Mile",
    "American History X",
    "Memento",
    "The Breakfast Club",
    "The Shawshank Redemption",
    "The Avengers",
    "Harry Potter and the Deathly Hallows: Part 1",
    "The Twilight Saga: Eclipse",
    "Eternal Sunshine of the Spotless Mind",
    "The Giver",
    "Raiders of the Lost Ark",
    "The Prestige",
    "The Departed",
    "The Lord of the Rings: The Two Towers",
    "Forrest Gump",
    "A Few Good Men",
    "The Maze Runner: The Scorch Trials",
    "Indiana Jones and the Last Crusade",
    "Deadpool",
    "The Big Lebowski",
    "Avatar",
    "Star Wars: Episode VI - Return of the Jedi",
    "Pulp Fiction",
    "A Clockwork Orange",
    "Harry Potter and the Order of the Phoenix",
    "Inglourious Basterds",
    "The Matrix Revolutions",
    "Django Unchained",
    "The Dark Knight",
    "The Hobbit: The Desolation of Smaug",
    "The Fault in Our Stars",
    "Inception",
    "E.T. the Extra-Terrestrial",
    "Jurassic Park",
    "Titanic",
    "Jaws",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "Harry Potter and the Chamber of Secrets",
    "Schindler's List",
    "No Country for Old Men",
    "The Perks of Being a Wallflower",
    "The Usual Suspects",
]
